language: python

python:
  - "2.7"

install:
  - pip install https://github.com/ahlmss/pkglib/archive/master.zip
  - pip install https://github.com/pythonpro-dev/pp-pkglib/archive/master.zip
  - python setup.py install

script: python setup.py test
