language: python

python:
  - "2.7"

branches:
  only:
    - master

env:
    - PKGLIB=/tmp/pkglinb.ini

pre_install:
    - echo "" > /tmp/pkglin.ini

install:
  - pip install -r travisci-reqs.txt

script: python setup.py test
